Report parser feature
SmartTechnologyLab/backend pull request #1
Opened 2024-05-04 21:40 UTC by ZadorozhnyiYevhenii

2024-05-12 10:04 UTC, P0TER approved these changes

2024-08-05 18:06 UTC, P0TER requested changes

2024-08-05 18:06 UTC, P0TER commented on src/report/report.service.ts
> +        ticker = ticker?.replace('.BLOCKED', '');
nit: тут обсуждали, что можно рассматривать эти тикеры как ИПО и проводить с ними отдельно операции, если возможно, если и так работает, то можно оставить

2024-08-05 18:06 UTC, P0TER commented on src/report/report.service.ts
> +      if (ticker?.endsWith('.US')) {
может разделять по точке и брать первую часть, а то если будут любые другие акции из других стран, то задолбемся прописывать суфиксы)

2024-08-05 18:06 UTC, P0TER commented on src/report/report.service.ts
> +                quantity: foundShortBuy.q,
наверно, не стоит размазывать данные файла по коду, лучше сразу трансформировать данные под твои нужды. 
просто когда формат данных у брокера изменится, тебе придется сейчас везде заменять. а так только в одном месте.

2024-08-05 18:31 UTC, ZadorozhnyiYevhenii commented on src/report/report.controller.ts
> +  private filePath23 = path.join(__dirname, '..', '..', '23.json');
Да

2024-08-05 18:32 UTC, ZadorozhnyiYevhenii commented on src/report/report.service.ts
> +      if (ticker?.endsWith('.US')) {
Разумно)

2024-09-05 13:58 UTC, P0TER approved these changes

2024-09-05 13:58 UTC, P0TER commented on src/main.ts
> +  await app.listen(process.env.PORT || 3000);
гуд

2024-09-05 13:58 UTC, P0TER commented on src/report/spec/report.service.spec.ts
> +jest.mock('../../currencyExchange/currencyExchange.service', () => {
надо будет потом на витест перейти если бекенд можно тестировать)

2024-09-05 13:58 UTC, P0TER commented on src/report/helpers/index.ts
> +  return sort(byDate, report);
не знаю или можно уже пользоваться, есть уже toSorted или как-то так метод называется

2024-09-05 13:58 UTC, P0TER commented on src/report/report.service.ts
> +      return { ...deal, instr_nm: ticker };
О намного красивее стало)

2024-09-05 13:58 UTC, P0TER commented on src/report/report.service.ts
> +        throw new BadRequestException('Not enough buy deals');
Наверно просто delas бо может нехватать и шортов)

2024-09-05 13:58 UTC, P0TER commented on package.json
> +      "pretty-quick --staged"
это чтобы только те файлы которые изменились проверять? прикольно

2024-09-05 13:58 UTC, P0TER commented on src/normalizeTrades/normalizeTrades.service.ts
> +  // getReportByStockExchange<T>(report: T, stockExchange: StockExchange) {
тут код закоментирован он не нужен?

2024-09-05 13:58 UTC, P0TER commented on src/report/report.controller.ts
> +  @ApiResponse({
Ошибку тоже можно описать

2024-09-05 14:02 UTC, ZadorozhnyiYevhenii commented on src/report/spec/report.service.spec.ts
> +jest.mock('../../currencyExchange/currencyExchange.service', () => {
Просто подефолту nest предлагает использовать jest)

2024-09-05 14:02 UTC, ZadorozhnyiYevhenii commented on src/report/helpers/index.ts
> +  return sort(byDate, report);
Есть, но у меня его не было в автодополнении, решил с рамды взять) И плюс он же делает не глубокую копию

2024-09-05 14:03 UTC, ZadorozhnyiYevhenii commented on src/report/report.service.ts
> +        throw new BadRequestException('Not enough buy deals');
Согласен)

2024-09-05 14:04 UTC, ZadorozhnyiYevhenii commented on package.json
> +      "pretty-quick --staged"
Да, имено так

2024-09-05 14:04 UTC, ZadorozhnyiYevhenii commented on src/normalizeTrades/normalizeTrades.service.ts
> +  // getReportByStockExchange<T>(report: T, stockExchange: StockExchange) {
Надо будет глянуть)

2024-09-05 14:04 UTC, ZadorozhnyiYevhenii commented on src/report/report.controller.ts
> +  @ApiResponse({
Гуд, опишу

2024-09-05 14:10 UTC, merged